// STRINGS
export const STRINGS = {
  FULL_NAME_ERROR: "Please enter full name",
  PHONE_ERROR: "Please enter a correct phone number",
  EMAIL_ERROR: "Please enter valid email",
  COUNTRY_ERROR: "Please choose country code",
  EMPTY_PHONE_ERROR: "Please Provide a Phone number!",
  EMPTY_EMAIL_ERROR: "Please Fill All the details!",
  PASSWORD_ERROR: "Please Provide a Password!",
  INCORRECT_PASSWORD:
    "Password should be at least 8 characters, one uppercase and one special character and one number",
  VERIFY_REQUIRE: "Please Provide Required Details!",
  OTP_VERIFY: "Please enter OTP",
  SIGNUP_TITLE: "Please enter your personal details below",
  ALREADY_TITLE: "Already have an account? ",
  AGREE_TITLE: "by signing up you agree with our ",
  TERMS_CONDITIONS: "Terms and Conditions.",
  LOGIN: "Login",
  SIGNUP: "Signup",
  SIGN_UP: "Sign up",
  START_TITLE: "Frame Device",
  START_INST_TITLE: "Tap & Pair Your Frame Device with Frame App",
  START_TUTORIAL_TITLE: "Skip Tutorial",
  ENSURE_TITLE: "Ensure Bluetooth & Wifi is on",
  LETS_PAIR_TITLE: "Let’s Pair Your\nDevice",
  SUBMIT: "Submit",
  OK: "Ok",
  CONNECT: "Connect",
  UPDATE: "Update",
  UPDATE_PROFILE: "Update Profile",
  UNPAIR_DEVICE: "Unpair Device",
  UPDATE_DEVICE_FIRMWARE: "Update Device Firmware",
  START_LIVE: "Start Live",
  LICENSE: "License Agreement",
  PRIVACY: "Data Privacy",
  HELP: "Help",
  CHOOSE_GALLARY: "Choose from Gallery",
  CANCEL: "Cancel",
  VERIFY_OTP_TEXT: "Verify Phone",
  SEND_OTP: "We have send otp to your phone\nno.",
  SUCCESS_TEXT: "Success",
  SUCCESS_LOGIN: "Congratulations, successfully login",
  INVITE_CONTACT: "Invite Contacts",
  STREAMER: "Streamer",
  AUDIENCE: "Audience",
  SHARE_LINK: "Share Link",
  NO_CONTACT_LIST: "No Contact List found",
  VERIFY_NOW: "Verify Now",
  RESEND_OTP: "Resend OTP",
  WELCOME_TO_APP: "Welcome to Frame App",
  DONT_HAVE_ACCN: "Don't have an account?",
  SEARCH_MEDIA: "Search media",
  RENAME: "Rename",
  DOWNLOAD: "Download",
  DELETE: "Delete",
  SIGNUP_AND: "Sign up and",
  START_LIVE_STREAMING: "Start live streaming",
  BROADCAST_YOUR_LIFE: "Broadcast your life as it happens",
  PROFILE_IMAGE_SUCCESS: "Profile image uploaded successfully",
  PROFILE_IMAGE_ERROR: "There is some error",
  MONOCLE_CONNECTED: "Monocle is connected successfully",
  ALERT: "Alert",
  ALERT_LOGOUT: "Are you want to logout?",
  CLOSE: "Close",
  PAIR_NOW: "Pair now",
  FIRMWARE_UPDATE_PAIR: "Pair with your Monocle to update firmware.",
};

export const ASYNC_CONST = {
  userId: "userId",
  accessToken: "accessToken",
  phone: "phone",
};
