// STRINGS
export const STRINGS = {
  FULL_NAME_ERROR: "Please enter full name",
  PHONE_ERROR: "Please enter a correct phone number",
  EMAIL_ERROR: "Please enter valid email",
  COUNTRY_ERROR: "Please choose country code",
  EMPTY_PHONE_ERROR: "Please Provide a Phone number!",
  EMPTY_EMAIL_ERROR: "Please Fill All the details!",
  PASSWORD_ERROR: "Please Provide a Password!",
  ENTER_WIFI_PASS: "Enter your Wifi password",
  INCORRECT_PASSWORD:
    "Password should be at least 8 characters, one uppercase and one special character and one number",
  VERIFY_REQUIRE: "Please Provide Required Details!",
  OTP_VERIFY: "Please enter OTP",
  SIGNUP_TITLE: "Your details will only be used for login",
  ALREADY_TITLE: "Already have an account? ",
  AGREE_TITLE: "by signing up you agree with our ",
  TERMS_CONDITIONS: "Terms and Conditions.",
  LOGIN: "Login",
  SIGNUP: "Signup",
  SIGN_UP: "Sign up",
  START_TITLE: "Frame Device",
  START_INST_TITLE: "Tap & Pair Your Frame Device with Frame App",
  START_TUTORIAL_TITLE: "Skip Tutorial",
  ENSURE_TITLE: "Ensure Bluetooth & Wifi is on",
  LETS_PAIR_TITLE: "Let’s Pair Your\nDevice",
  SUBMIT: "Submit",
  OK: "Ok",
  CONNECT: "Connect",
  UPDATE: "Update",
  UPDATE_PROFILE: "Update Profile",
  UNPAIR_DEVICE: "Unpair Device",
  UPDATE_DEVICE_FIRMWARE: "Update Device Firmware",
  START_LIVE: "Start Live",
  LICENSE: "License Agreement",
  PRIVACY: "Data Privacy",
  HELP: "Help",
  CHOOSE_GALLARY: "Choose from Gallery",
  CANCEL: "Cancel",
  VERIFY_OTP_TEXT: "Verify Phone",
  SEND_OTP: "We have send otp to your phone\nno.",
  SUCCESS_TEXT: "Success",
  SUCCESS_LOGIN: "Congratulations, successfully login",
  INVITE_CONTACT: "Invite Contacts",
  STREAMER: "Streamer",
  AUDIENCE: "Audience",
  SHARE_LINK: "Share Link",
  NO_CONTACT_LIST: "No Contact List found",
  VERIFY_NOW: "Verify Now",
  RESEND_OTP: "Resend OTP",
  LOGIN_TEXT: "Enter your phone number and we’ll text you a code",
  DONT_HAVE_ACCN: "Don't have an account?",
  SEARCH_MEDIA: "Search media",
  RENAME: "Rename",
  DOWNLOAD: "Download",
  DELETE: "Delete",
  LETS_GO_HEADING: "Let’s get you set up",
  LETS_GO_TITLE: "Sign up, or login with your phone number",
  // BROADCAST_YOUR_LIFE: "Broadcast your life as it happens",
  PROFILE_IMAGE_SUCCESS: "Profile image uploaded successfully",
  PROFILE_IMAGE_ERROR: "There is some error",
  MONOCLE_CONNECTED: "Monocle is connected successfully",
  FRAME_CONNECTED: "Frame is connected successfully",
  ALERT: "Alert",
  ALERT_LOGOUT: "Are you want to logout?",
  CLOSE: "Close",
  PAIR_NOW: "Pair now",
  FIRMWARE_UPDATE_PAIR: "Pair with your Monocle to update firmware.",
  CHOOSE_WIFI_NETWORK: "Choose Your Personal Network :",
  UPDATE_FIRMWARE: "Update Firmware",
  ZIP_FILE_SUPPORTED: "Only zip file is supported",
  CANCEL_PICKER: "You cancelled the picker",
  FILE_SELECTED: "File Selected: ",
  SELECT_UPDATE_FILE: "Select Update File",
  PERFORM_FIRMWARE_UPDATE: "Perform Firmware Update",
  CONNECT_TEXT: "Bring your Monocle close to your phone",
  WELCOME: "Welcome",
  WELCOME_TEXT: "The pocket sized AR device for imaginative hackers",
  BRILLIANT_TEXT:"BRILLIANT"

};

//micro python command
export const COMMAND = {
  X3: "\x03",
  X1: "\x01",
  IMPORT_CAMERA: "from machine import Camera \nprint('IMPORT')\x04",
  CAMERA_CAPTURE: "Camera.capture() \nprint('SCAN') \x04",
  WIFI_STATUS: "p=WiFi.status() \nprint('STATUS') \nprint(p)\x04",
  WIFI_LIST: "p=WiFi.list() \nprint('LIST') \nprint(p)\x04",
};

export const ASYNC_CONST = {
  userId: "userId",
  accessToken: "accessToken",
  phone: "phone",
};
